# The URL the site will be built for
base_url = "https://oxechicao.github.io/da-lama-ao-caos"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "base16-ocean-dark"


[[extra.profile.social]]
name = "GitHub"
url = "https://github.com/oxechicao"

[[extra.profile.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/fthiagogv/"

[[extra.profile.social]]
name = "Dev.to"
url = "https://dev.to/ftgv_"

[[extra.profile.social]]
name = "Repo"
url = "https://github.com/oxechicao/manguetown"

[[extra.menus]]
name = "In√≠cio"
url = "/"

[[extra.menus]]
name = "Cookbook"
url = "/cookbook/"
